apiVersion: v1
kind: Service
metadata:
  name: kibana-lb
  namespace: efk
spec:
  selector: 
    app: kibana
  type: LoadBalancer  
  ports:
    - port: 8080
      targetPort: 5601 
      #nodePort: 30000